# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.16'

    - name: yarn install, yarn lint, yarn build
      run: |
        yarn install
        yarn lint
        yarn build
  
    - name: truffle template
      run: |
        cd templates/truffle
        yarn install
        yarn lint:js
        yarn lint:sol
        yarn compile
        yarn test

    - name: buidler template
      run: |
        cd templates/buidler
        yarn install
        yarn lint:js --if-present
        yarn lint:sol --if-present
        yarn compile
        yarn test
