name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  cli:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.16'

    - name: yarn install, yarn lint, yarn build
      run: |
        yarn install
        yarn lint
        yarn build

  truffle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.16'

    - name: truffle template
      run: |
        cd templates/truffle
        yarn install
        yarn lint:js
        yarn lint:sol
        yarn compile
        yarn test

  buidler:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.16'

    - name: buidler template
      run: |
        cd templates/buidler
        yarn install
        yarn compile
        yarn test
